"use client";

import { useCallback, useEffect, useRef, useState } from "react";

interface WikiSection {
  id: string;
  title: string;
  content: string;
}

const DEFAULT_SECTIONS: WikiSection[] = [
  {
    id: "architecture",
    title: "Architecture Overview",
    content: `<strong>Tech Stack:</strong> Next.js 16 (App Router) + React 19 + TypeScript + Tailwind CSS v4 on Vercel. Drupal 11 (headless) + Commerce 3 + PostgreSQL 16 on Ubuntu 24.04 VPS (72.62.80.155).

<strong>Data Flow:</strong> Browser → Next.js API Routes → Drupal JSON:API → PostgreSQL. Browser never calls Drupal directly.

<strong>External Services:</strong> Stripe Connect (payments), Printful (POD fulfillment), X API v2 (identity/content), Grok Imagine (AI image generation), Brevo SMTP (email), Telnyx (SMS), Cloudflare (DNS).

<strong>Repo:</strong> github.com/rareimagery/x-store-frontend (Next.js) + rareimage_back (Drupal)`,
  },
  {
    id: "env-vars",
    title: "Environment Variables",
    content: `<strong>Required (Vercel):</strong>
• DRUPAL_API_URL — http://72.62.80.155
• DRUPAL_API_USER / DRUPAL_API_PASS — Drupal Basic Auth
• NEXTAUTH_SECRET / NEXTAUTH_URL — JWT signing
• X_CLIENT_ID / X_CLIENT_SECRET — X OAuth 2.0
• X_API_BEARER_TOKEN — X API v2 app-level
• STRIPE_SECRET_KEY — Stripe payments
• CRON_SECRET — Vercel cron auth

<strong>Optional:</strong>
• XAI_API_KEY / GROK_API_KEY — Grok Imagine
• CLOUDFLARE_API_TOKEN — DNS provisioning
• SMTP_HOST / SMTP_USER / SMTP_PASS — Brevo email
• TELNYX_API_KEY — SMS
• ADMIN_X_USERNAMES — Comma-separated admin handles
• FACEBOOK_CLIENT_ID / SECRET, GOOGLE_CLIENT_ID / SECRET — Social OAuth`,
  },
  {
    id: "drupal-backend",
    title: "Drupal Backend",
    content: `<strong>Server:</strong> Ubuntu 24.04, Nginx, PHP 8.3 FPM, PostgreSQL 16 at 72.62.80.155
<strong>Drupal:</strong> 11.3.5 at /var/www/html/mysite, served on port 80
<strong>Database:</strong> drupaldb on localhost:5432 (user: drupal), currently ~50MB
<strong>Drush:</strong> v13.7.2 at vendor/bin/drush

<strong>Custom Modules (5):</strong>
• x_profile_auto_importer — On user registration, creates x_user_profile node + Commerce store
• x_profile_sync — X API profile lookup/sync endpoints
• rareimagery_cost_dashboard — Cost tracking, Cloudflare analytics, budget monitoring
• rareimagery_grok_creator_studio — Grok Imagine usage logging per creator
• rareimagery_printful_sync — Server-side Printful product import (POST /api/printful-sync/{uuid})
• rareimagery_invite_gate — Invite code generation, validation, redemption

<strong>Content Model:</strong>
• Node: x_user_profile (15 fields: username, bio, pfp, followers, verified, etc.)
• Commerce Store: online — field_x_user_profile, field_printful_api_key, field_store_slug
• Commerce Products: clothing (with t_shirt/hoodie/ballcap variation types)
• Attributes: color (17 values), size (10 values)`,
  },
  {
    id: "auth",
    title: "Authentication & Roles",
    content: `<strong>Primary:</strong> X (Twitter) OAuth 2.0 via NextAuth 4.x
<strong>Secondary:</strong> Google OAuth, Facebook OAuth
<strong>Fallback:</strong> Drupal credentials (admin/DrupalAdmin2026)
<strong>Planned:</strong> TikTok, Instagram (providers configured, buttons removed from UI)

<strong>Session Fields:</strong> xUsername, xId, storeSlug, role, providerType, socialDisplayName

<strong>Roles:</strong>
• admin — X accounts in ADMIN_X_USERNAMES env var. Full console + admin panel.
• creator — Any X login. Console for their own store only.

<strong>Invite Gate:</strong> Signup requires a RARE-XXXXXXXX invite code validated against Drupal before OAuth proceeds. Codes are single-use, generated by admin at /console/admin/invites.

<strong>Subscription Gate:</strong> X Creator Subscription to @RareImagery ($4/month) checked on first login. Infrastructure failures fail-open.`,
  },
  {
    id: "console-pages",
    title: "Console Dashboard Pages",
    content: `<strong>Workspace:</strong>
• Page Building — Drag-and-drop wireframe editor (Main Content + Right Sidebar)
• Grok Creator Studio — AI-powered design studio with 4 input modes (see below)
• Grok Library — Upload/manage Grok Imagine creations (images + videos)
• My Favorites — Curate X creators into categorized collections
• Social Feeds — Connect TikTok, Instagram, YouTube accounts
• Music — Spotify + Apple Music playlist builder
• X Communities — Showcase X Communities
• X Articles — Import long-form X articles

<strong>Grok Creator Studio (/console/design-studio):</strong>
Tabbed interface with 4 ways to start a design:
• <strong>Write a Prompt</strong> — Type a description + "Enhance with Grok AI" button (uses grok-3-mini to rewrite prompt and auto-generate product description)
• <strong>From X Profile</strong> — Enter any @username, auto-fills prompt from their bio + uses PFP as reference
• <strong>From X Post</strong> — Paste any X post URL, extracts text as prompt + first image as reference (POST /api/design-studio/import-post)
• <strong>Upload Image</strong> — Drag-and-drop reference image (JPEG/PNG/WebP, max 4MB)
Then: select product type (T-Shirt, Hoodie, Ballcap, Digital Drop) → Generate 4 Grok Imagine variants → select favorite → publish to Printful + Drupal Commerce → Share to X
APIs: /api/design-studio/generate, /api/design-studio/publish, /api/design-studio/enhance, /api/design-studio/import-post

<strong>Store (dropdown):</strong>
• Products, Orders, Shipping, Accounting, Printful, Settings

<strong>Platform Admin (admin only):</strong>
• All Stores — Approve/reject/suspend stores
• Users — View all accounts and stores
• X Subscribers — Manage subscription tiers
• Cost Dashboard — Platform cost tracking
• Invite Codes — Generate and manage invite codes`,
  },
  {
    id: "payments",
    title: "Payments & Fees",
    content: `<strong>Payment Processor:</strong> Stripe Connect Express (per-store accounts). X Money adapter stubbed for future.

<strong>Fee Structure:</strong>
• X Creator Subscription: $4/month to @RareImagery on X (platform access)
• Store maintenance: $2/month (recurring, cancellable)
• Payment processing: $0.30/transaction (Stripe or X Money when launched)
• No per-order platform fees, no listing fees

<strong>Stripe Connect Flow:</strong>
Customer pays → Platform Stripe receives → application_fee deducted → transfer to creator's Connect account.

<strong>PaymentProvider Interface:</strong> payments.ts abstracts Stripe vs X Money. X Money preferred when available, falls back to Stripe.`,
  },
  {
    id: "printful",
    title: "Printful Integration",
    content: `<strong>Per-Store Keys:</strong> Each creator connects their own Printful Private Token (field_printful_api_key on store entity).

<strong>Auto-Sync on Connect:</strong> When a creator saves their Printful key via /api/printful/connect, it fires a POST to Drupal's /api/printful-sync/{uuid} which runs server-side (no serverless timeouts).

<strong>Product Types:</strong> t_shirt, hoodie, ballcap — determined by product name keywords.

<strong>Sync Logic (Drupal module):</strong>
1. Fetches all products from creator's Printful store
2. Skips already-imported (by field_printful_product_id)
3. Creates variations with color/size attributes (creates missing values)
4. Downloads + attaches thumbnail images
5. Updates titles if changed on Printful

<strong>Cron Sync:</strong> Code audit agent triggers /api/printful-sync-all every 6 hours for all connected stores.

<strong>Color-Matched Images:</strong> Per-variation field_variant_front_url and field_variant_back_url for gallery swapping on color selection.`,
  },
  {
    id: "wireframe",
    title: "Page Builder (Wireframe System)",
    content: `<strong>Layout:</strong> 2-column — Main Content (3/4 width) + Right Sidebar (1/4 width). Left sidebar removed.

<strong>Block Types (16):</strong>
Product Grid, Pinned Post, Social Feed, Music Player, X Articles, Grok Gallery, X Communities, TikTok/Instagram/YouTube embeds, My Favorites, Top Followers, Hero Banner, Text Block, CTA Section, Video Embed, Testimonial, Newsletter, Spacer, Image Gallery, Donation

<strong>Compact Mode:</strong> Right sidebar blocks receive compact=true — people blocks show 2-across, image blocks show 1-across.

<strong>Color Schemes (10):</strong> Midnight, Ocean, Forest, Sunset, Royal, Cherry, Arctic, Ember, Slate, Neon

<strong>Page Backgrounds (9):</strong> Nature, Mountain, Space, Ocean Waves, City Night, Desert, Aurora, Abstract + custom upload

<strong>Storage:</strong> Layouts saved as JSON documents to Drupal via /api/builds. Published builds render on the public creator page.`,
  },
  {
    id: "public-pages",
    title: "Public Pages",
    content: `<strong>Creator Homepage:</strong> /[creator] — Wireframe layout with profile header, nav menu, content blocks
<strong>Store:</strong> /[creator]/store — Product catalog grid
<strong>Favorites:</strong> /[creator]/favorites — 6-across grid with X API enrichment (pinned + 2 recent posts)
<strong>Gallery:</strong> /[creator]/gallery — "Grok Library" 6-across grid with hover overlays
<strong>Articles:</strong> /[creator]/articles — Long-form X articles with engagement stats

<strong>Nav Bar:</strong> Home | Store | Favorites | Gallery | Articles | [Open Your Store → /login] | [Here's How → /howto] | [X Share]

<strong>Product Detail:</strong> /products/[slug] — Color-matched image gallery, size/color selection, add to cart

<strong>How-To Guide:</strong> /howto — Creator onboarding wiki with admin inline editing
<strong>Admin Wiki:</strong> /admin/wiki — Platform documentation (admin-only access)`,
  },
  {
    id: "api-routes",
    title: "Next.js API Routes",
    content: `<strong>Auth:</strong> /api/auth/[...nextauth]
<strong>Stores:</strong> /api/stores/create, /api/stores/products, /api/stores/import-x-data, /api/stores/approve
<strong>Console:</strong> /api/console/stores, /api/console/active-store, /api/console/insights
<strong>Printful:</strong> /api/printful/connect, /api/printful/import, /api/printful/sync-drupal, /api/printful/status, /api/printful/products, /api/printful/catalog, /api/printful/orders, /api/printful/shipping-rates, /api/printful/webhook
<strong>Social:</strong> /api/social/follow, /api/social/followers, /api/social/picks, /api/social/shoutouts, /api/social/seed-from-x
<strong>Content:</strong> /api/favorites, /api/favorites/enrich, /api/gallery, /api/gallery/upload, /api/articles, /api/music, /api/communities, /api/social-feeds, /api/blocks, /api/builds
<strong>Design:</strong> /api/design-studio/generate, /api/design-studio/publish, /api/design-studio/enhance, /api/design-studio/import-post
<strong>Payments:</strong> /api/checkout, /api/webhooks/stripe, /api/subscriptions/*
<strong>Admin:</strong> /api/invite/admin, /api/guide
<strong>Other:</strong> /api/health, /api/x-lookup, /api/upload, /api/notifications/preferences`,
  },
  {
    id: "cron-agents",
    title: "Automated Agents",
    content: `<strong>3 Cron Jobs (Vercel):</strong>

• <strong>Code Audit</strong> — Every 6 hours (0,6,12,18 UTC)
  30+ health checks: all env vars, Drupal connectivity (JSON:API, stores, products, variations, session auth), all public pages, NextAuth, X API, Grok, Stripe, Drupal cache/cron, Printful sync-all, HTTPS validation, Stripe key type. Email alert on critical.

• <strong>Wiki Sync</strong> — Every 12 hours (3,15 UTC)
  Scans /howto guide for stale content (old URLs, wrong pricing, outdated feature counts). Auto-fixes while preserving admin edits.

• <strong>X Money Watcher</strong> — Every 12 hours (6,18 UTC)
  Probes X Money API endpoints. Alerts when they go live.

<strong>Legacy agents (removed, consolidated into Code Audit):</strong>
frontend-agent, api-agent, drupal-api-path-agent, site-generate-agent`,
  },
  {
    id: "drupal-modules",
    title: "Drupal Custom Modules",
    content: `<strong>x_profile_auto_importer:</strong> hook_user_insert creates x_user_profile node + Commerce store on registration.

<strong>x_profile_sync:</strong> REST endpoints for X profile lookup/sync. Used by Next.js for profile data.

<strong>rareimagery_cost_dashboard:</strong> CostTracker service, CloudflareAnalyticsService, ExternalVideoCostService. Tables: rareimagery_costs, rareimagery_external_video_costs. REST endpoint: /api/cost-summary.

<strong>rareimagery_grok_creator_studio:</strong> GrokUsageLogger service. Table: rareimagery_grok_usage. Tracks per-creator Grok Imagine costs.

<strong>rareimagery_printful_sync:</strong> PrintfulSyncController. POST /api/printful-sync/{uuid} and /api/printful-sync-all. Server-side product import with color/size attributes.

<strong>rareimagery_invite_gate:</strong> InviteController. POST /api/invite/generate, /api/invite/validate, /api/invite/redeem, GET /api/invite/list. Table: rareimagery_invite_codes.`,
  },
  {
    id: "infrastructure",
    title: "Infrastructure & Deployment",
    content: `<strong>Frontend:</strong> Vercel auto-deploys on push to main. Domain: rareimagery.net + *.rareimagery.net

<strong>Backend:</strong> SSH root@72.62.80.155 → su - rare → /var/www/html/mysite
• Nginx on port 80, PHP 8.3 FPM, PostgreSQL 16 (native, not Docker)
• Drush: vendor/bin/drush cr / vendor/bin/drush cron
• Deploy modules: scp to /var/www/html/mysite/web/modules/custom/ → drush en module_name → drush cr

<strong>Disk:</strong> 96GB total, ~3.2GB used. DB: ~50MB. Drupal files: ~8MB.

<strong>DNS:</strong> Cloudflare manages rareimagery.net. Wildcard to Vercel. Per-store subdomains via proxy.ts middleware rewrite.

<strong>Caches:</strong> Next.js s-maxage=60 stale-while-revalidate=300 for general content. No-store for auth and store routes. Drupal cache cleared by code-audit agent every 6 hours.`,
  },
];

export default function WikiClient() {
  const [sections, setSections] = useState<WikiSection[]>(DEFAULT_SECTIONS);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const mainRef = useRef<HTMLDivElement>(null);

  // Load saved overrides
  useEffect(() => {
    fetch("/api/admin/wiki")
      .then((r) => r.json())
      .then((d) => {
        if (d.sections && Array.isArray(d.sections) && d.sections.length > 0) {
          setSections(d.sections);
        }
      })
      .catch(() => {});
  }, []);

  const saveWiki = useCallback(async () => {
    if (!mainRef.current) return;
    setSaving(true);

    // Collect edited content from contentEditable elements
    const updated = sections.map((s) => {
      const el = mainRef.current?.querySelector(`[data-section-id="${s.id}"]`);
      if (el) {
        return { ...s, content: el.innerHTML };
      }
      return s;
    });

    try {
      const res = await fetch("/api/admin/wiki", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sections: updated }),
      });
      if (res.ok) {
        setSections(updated);
        setEditing(false);
      }
    } catch {} finally {
      setSaving(false);
    }
  }, [sections]);

  // Scroll spy
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            setActiveSection(e.target.id);
          }
        }
      },
      { rootMargin: "-20% 0px -60% 0px" }
    );
    const els = document.querySelectorAll(".wiki-section");
    els.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  return (
    <div className="flex min-h-screen bg-zinc-950 text-white">
      {/* Sidebar TOC */}
      <nav className="fixed top-0 left-0 w-64 h-screen border-r border-zinc-800 bg-zinc-900/80 overflow-y-auto p-4">
        <div className="mb-6">
          <h2 className="text-sm font-bold text-indigo-400">Platform Wiki</h2>
          <p className="text-[10px] text-zinc-600 mt-1">Admin only</p>
        </div>
        <div className="space-y-0.5">
          {sections.map((s) => (
            <a
              key={s.id}
              href={`#${s.id}`}
              className={`block rounded-lg px-3 py-1.5 text-xs transition ${
                activeSection === s.id
                  ? "bg-indigo-600/20 text-indigo-400 font-medium"
                  : "text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50"
              }`}
            >
              {s.title}
            </a>
          ))}
        </div>

        <div className="mt-8 pt-4 border-t border-zinc-800">
          {!editing ? (
            <button
              onClick={() => setEditing(true)}
              className="w-full rounded-lg bg-indigo-600 px-3 py-2 text-xs font-medium text-white hover:bg-indigo-500 transition"
            >
              Edit Wiki
            </button>
          ) : (
            <div className="space-y-2">
              <button
                onClick={saveWiki}
                disabled={saving}
                className="w-full rounded-lg bg-green-600 px-3 py-2 text-xs font-medium text-white hover:bg-green-500 disabled:opacity-50 transition"
              >
                {saving ? "Saving..." : "Save Changes"}
              </button>
              <button
                onClick={() => setEditing(false)}
                className="w-full rounded-lg border border-zinc-700 px-3 py-2 text-xs font-medium text-zinc-400 hover:text-white transition"
              >
                Cancel
              </button>
            </div>
          )}
        </div>
      </nav>

      {/* Main content */}
      <main className="ml-64 flex-1 max-w-4xl px-8 py-10" ref={mainRef}>
        <div className="mb-8">
          <h1 className="text-3xl font-bold">RareImagery Platform Wiki</h1>
          <p className="text-sm text-zinc-500 mt-2">
            Complete platform documentation. {editing && <span className="text-indigo-400">Click any section to edit.</span>}
          </p>
        </div>

        {sections.map((section) => (
          <section key={section.id} id={section.id} className="wiki-section mb-8">
            <h2 className="text-lg font-bold text-white mb-3 pb-2 border-b border-zinc-800">
              {section.title}
            </h2>
            <div
              data-section-id={section.id}
              className={`text-sm text-zinc-400 leading-relaxed whitespace-pre-line ${
                editing
                  ? "outline outline-2 outline-dashed outline-zinc-700 rounded-lg p-4 focus:outline-indigo-500 hover:outline-zinc-600 bg-zinc-900/50 cursor-text"
                  : ""
              }`}
              contentEditable={editing}
              suppressContentEditableWarning
              dangerouslySetInnerHTML={{ __html: section.content }}
            />
          </section>
        ))}
      </main>
    </div>
  );
}
